---

code: BUAPI
name: My Business API
description: The decription of the business api
environments:
  - name: local
    url: http://host.docker.internal:8080
    default: true
    secrets:
      gogo: <FOO>
    data:
      channel: google-sheet 
      config:
        id: <GOOGLE_SHEET_ID>
        apikey: <GOOGLE_SHEET_APIKEY>
      startSymbol: '{['
      endSymbol: ']}'
    outputs:
      - type: http
        enabled: true
        config:
          url: 'https://httpdump.io/truyu'
      - type: file
        enabled: true
        config:
          path: 'my-report.json'
      - type: elastic-search
        enabled: false
        config:
          url: 'http://host.docker.internal:9200'
  - name: uat
    url: https://www.my-api-gateway.com
    outputs:
      - type: elastic-search
        enabled: true
        config:
          url: 'http://my-enterprise-elk:9200'
          index: 'custom-index-name'
      - type: http
        enabled: true
        config:
          url: 'https://custom-report-endpoint.com'
          method: 'POST'
