---

code: BUAPI
name: My Business API
description: The decription of the business api
environments:
  - name: local
    url: http://host.docker.internal:8000
    default: true
    reports:
      - type: http
        enabled: false
        config:
          path: 'https://httpdump.io/lb8f7'
      - type: file
        enabled: true
        config:
          path: 'my-report.json'
  - name: uat
    url: https://www.my-api-gateway.com
    reports:
      - type: elastic-search
        enabled: true
        config:
          url: 'http://my-enterprise-elk:9200'
          index: 'custom-index-name'
      - type: http
        enabled: true
        config:
          url: 'https://custom-report-endpoint.com'
          method: 'POST'
