---

environments:
  - name: local
    url: http://host.docker.internal:8000
    reports:
      - type: elastic-search
        config:
          url: 'http://host.docker.internal:9200'
          index: 'restqa-bdd-rest-api'
      - type: http
        config:
          url: 'https://httpdump.io/lb8f7'
          method: 'POST'
  - name: uat
    url: http://34.71.230.96
    reports:
      - type: elastic-search
        config:
          url: 'http://34.71.181.81:9200'
          index: 'restqa-bdd-rest-api'

