name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
    - name: "Trigger the update of the documentation"
      run: curl --request POST --url https://api.github.com/repos/restqa/documentation/actions/workflows/deploy.yml/dispatches --header 'Accept: application/vnd.github.everest-preview+json' --header 'Content-Type: application/json' --data '{"ref": "master"}' -u $GH_USERNAME:$GH_PASSWORD
      
